version: '3.8'

services:
  # Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME:-desd_db}
      MYSQL_USER: ${DB_USER:-desd_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-desd_pass_123}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  # Backend
  backend:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SECRET_KEY=2jSD9r2-KTldmeaVwm1QQx7qVyf4sRgJ8o2k7-Y1m6DZW5eoVcNIDJsEDpiPttz3c7g
      - DEBUG=True
      - DB_NAME=desd_db
      - DB_USER=desd_user
      - DB_PASSWORD=desd_pass_123
      - DB_ROOT_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 --insecure"

  # Frontend
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "echo '#!/bin/sh' > ./start.sh &&
            echo 'npm install' >> ./start.sh &&
            echo 'export WATCHPACK_POLLING=true' >> ./start.sh &&
            echo 'npm start -- --polling' >> ./start.sh &&
            chmod +x ./start.sh && 
            ./start.sh"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
      - FAST_REFRESH=true
      - CI=false
    depends_on:
      - backend

volumes:
  mysql_data:
  frontend_node_modules: