# Generated by Django 5.2 on 2025-04-16 09:56

import claims.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ClaimAttachment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to=claims.models.claim_file_path)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("DOCUMENT", "Document"),
                            ("AUDIO", "Audio"),
                            ("VIDEO", "Video"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="claims.claim",
                    ),
                ),
            ],
        ),
    ]
