# Generated by Django 5.2 on 2025-04-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_reference_number_claimattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='reference_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='ClaimAttachment',
        ),
    ]
