# Generated by Django 5.2 on 2025-05-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_decided_settlement_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
