# Generated by Django 5.2 on 2025-04-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("PENDING", "Pending"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
    ]
