# Generated by Django 5.2 on 2025-05-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_approval_status"),
        ("finance", "0002_insurancecompany_billingrecord_claim_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="insurance_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="finance.insurancecompany",
            ),
        ),
    ]
