# Generated by Django 4.2 

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_insurancecompany_billingrecord_claim_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_claim', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billing_rates', to=settings.AUTH_USER_MODEL)),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_rates', to='finance.insurancecompany')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('insurance_company',), name='unique_active_rate_per_company'),
        ),
    ]